-- Database Schema for ISGA Chat (Group + Private Messaging)

-- Users table
CREATE TABLE IF NOT EXISTS USER (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    PERMISSION INT NOT NULL DEFAULT 3,
    LAST_CONNECTION_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'offline',
    IS_BANNED BOOLEAN DEFAULT FALSE
);

-- Group messages (existing)
CREATE TABLE IF NOT EXISTS MESSAGE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INT,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONTENT TEXT NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

-- Activity logs (existing)
CREATE TABLE IF NOT EXISTS LOG (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INT,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TYPE VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

-- NEW: Contacts table (for WhatsApp-style contact list)
CREATE TABLE IF NOT EXISTS CONTACT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INT NOT NULL,
    CONTACT_USER_ID INT NOT NULL,
    CONTACT_NAME VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID),
    FOREIGN KEY (CONTACT_USER_ID) REFERENCES USER(ID),
    UNIQUE(USER_ID, CONTACT_USER_ID)
);

-- NEW: Private messages table
CREATE TABLE IF NOT EXISTS PRIVATE_MESSAGE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SENDER_ID INT NOT NULL,
    RECEIVER_ID INT NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_READ BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (SENDER_ID) REFERENCES USER(ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USER(ID)
);

-- NEW: Conversations view helper (to get latest message per conversation)
CREATE INDEX IF NOT EXISTS idx_private_message_sender ON PRIVATE_MESSAGE(SENDER_ID);
CREATE INDEX IF NOT EXISTS idx_private_message_receiver ON PRIVATE_MESSAGE(RECEIVER_ID);
CREATE INDEX IF NOT EXISTS idx_contact_user ON CONTACT(USER_ID);

-- Seed Data (Passwords are SHA-256 of 'password123')
INSERT OR IGNORE INTO USER (USERNAME, FIRST_NAME, LAST_NAME, EMAIL, PASSWORD, PERMISSION) VALUES
('admin', 'Admin', 'User', 'admin@isga.com', 'ef92b778bafe421e592022c3904a0a1e36601e444400e96030c6aee6ad005fbc', 1),
('mod', 'Moderator', 'User', 'mod@isga.com', 'ef92b778bafe421e592022c3904a0a1e36601e444400e96030c6aee6ad005fbc', 2),
('user1', 'Normal', 'User1', 'user1@isga.com', 'ef92b778bafe421e592022c3904a0a1e36601e444400e96030c6aee6ad005fbc', 3),
('user2', 'Normal', 'User2', 'user2@isga.com', 'ef92b778bafe421e592022c3904a0a1e36601e444400e96030c6aee6ad005fbc', 3),
('nidal', 'Nidal', 'Targhy', 'nidal@isga.com', 'ef92b778bafe421e592022c3904a0a1e36601e444400e96030c6aee6ad005fbc', 3),
('mourad', 'Mourad', 'Sultan', 'mourad@isga.com', 'ef92b778bafe421e592022c3904a0a1e36601e444400e96030c6aee6ad005fbc', 3);
